web/urls.py
from django.urls import path
from . import views

app_name = "web"

urlpatterns = [
    path("",views.index,name = "index"),
    path("about/",views.about_us,name = "about-us"),
    path("blog_single_with_sidebar/",views.blog_single_with_sidebar,name = "blog_single_with_sidebar"),
    path("blog_with_sidebar/",views.blog_with_sidebar,name = "blog_with_sidebar"),
    path("contact/",views.contact,name = "contact"),
    path("notfound/",views.notfound,name = "notfound"),
    path("index_startup/",views.index_startup,name = "index_startup"),
    path("project_details/",views.project_details,name = "project_details"),
    path("projects/",views.projects,name = "projects"),
    path("services_two/",views.services_two,name = "services_two"),
    path("services_details/",views.services_details,name = "services_details"),




]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from web import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls',namespace='web')),
   
]

web/models.py
from django.db import models
from versatileimagefield.fields import VersatileImageField


class Blog(models.Model):
     CATEGORY_CHOICES =(('agency','Agency'),('digital','Digital'),('branding','Branding'),)

     title = models.CharField(max_length=128)
     slug = models.SlugField(unique=True,blank=True, null=True)
     category = models.CharField(max_length=120,choices = CATEGORY_CHOICES,default="creative")
     content = models.TextField()
     author_name = models.CharField(max_length=120)
     featured_image = models.ImageField()
     description = models.TextField()
     image = models.ImageField()
     author = models.ForeignKey("Author",on_delete=models.CASCADE)

     def __str__(self):
        return str(self.title)


class Author(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField(blank=True,null=True)
    photo = models.ImageField()
    about = models.TextField()

    def __str__(self):
        return str(self.name)

     
class Contact(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField(blank=True,null=True)
    phone = models.CharField(max_length=120,blank=True,null=True)
    place = models.CharField(max_length=120,blank=True,null=True)
    message = models.TextField()

    def __str__(self):
        return str(self.name)
        
        
class Project(models.Model):
    CATEGORY_CHOICES =(('advertising','Advertising'),('branding','Branding'),)
        
    title = models.CharField(max_length=120)
    image = models.ImageField()
    category = models.CharField(max_length=120,choices = CATEGORY_CHOICES,default="branding")
    designation = models.CharField(max_length=120)
        
    def __str__(self):
        return str(self.title)
            
            
class Testimonial(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    image = models.ImageField
    name = models.CharField(max_length=120)

    def __str__(self):
        return str(self.title)  
        
      
class Slider(models.Model): 
    title = models.CharField(max_length=120)
    sub_title = models.CharField(max_length=120)
    link = models.URLField(max_length=190,blank=True)

    def __str__(self):
        return str(self.title)  
        
        
class Service(models.Model): 
    title = models.CharField(max_length=120)
    icon = models.FileField()
    description = models.TextField()
    
    def __str__(self):
        return str(self.title) 
        
            
            
            
        
        
        
        
        
        

web/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from .models import Blog,Contact,Service,Slider,Project,Testimonial,Author


def index(request):
    sliders = Slider.objects.all()
    context= {
        "is_index": True,
        "sliders": sliders,
        "number": 30,
    }
    return render(request,'web/index.html',context)


def about_us(request):
    context= {
        "is_abous_us":True
    }
    return render(request,'web/about-us.html',context)


def blog_single_with_sidebar(request):
    context= {
        "is_blog_single_with_sidebar":True
    }
    return render(request,'web/blog-single-with-sidebar.html',context)


def blog_with_sidebar(request):
    context= {
        "is_blog_with_sidebar":True
    }
    return render(request,'web/blog-with-sidebar.html',context)


def contact(request):
    context= {
        "is_contact":True
    }
    return render(request,'web/contact.html',context)


def index(request):
    context= {
        "is_index":True
    }
    return render(request,'web/index.html',context)


def index_startup(request):
    context= {
        "is_index_startup":True
    }
    return render(request,'web/index-startup.html',context)


def project_details(request):
    context= {
        "is_project_details":True
    }
    return render(request,'web/project-details.html',context)


def projects(request):
    context= {
        "is_projects":True
    }
    return render(request,'web/projects.html',context)


def services_two(request):
    context= {
        "is_services_2":True
    }
    return render(request,'web/services-2.html',context)


def services_details(request):
    context= {
        "is_services_details":True
    }
    return render(request,'web/services-details.html',context)


def notfound(request):
    context= {
        "is_notfound":True
    }
    return render(request,'web/404.html',context)

templates/includes/header-two.html
{% load static %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" >Pages</a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'web:about-us' %}">About Us</a></li>
                                
                                
                                <li><a href="{% url 'web:contact' %}">Contact Us</a></li>
                                <li><a href="{% url 'web:notfound' %}">Error Page</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" >Projects</a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'web:projects' %}">Projects Version One</a></li>
                              
                                <li><a href="{% url 'web:project_details' %}">Projects Details</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" >Services</a>
                            <ul class="dropdown-menu">
                                
                                <li><a href="{% url 'web:services_two' %}">Services Version Two</a></li>
                                
                                <li><a href="{% url 'web:services_details' %}">Services Details</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" >Blog</a>
                            <ul class="dropdown-menu">
                                
                                <li><a href="{% url 'web:blog_with_sidebar' %}">Blog With Sidebar</a></li>
                                
                              
                                <li><a href="{% url 'web:blog_single_with_sidebar' %}">Blog Single With Sidebar</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'web:contact' %}">contact</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>

            <!-- Start Side Menu -->
            <div class="side">
                <a href="#" class="close-side"><i class="icon_close"></i></a>
                <div class="widget">
                    <img src="{% static 'web/img/logo.png' %}" alt="Logo">
                    <p>
                        Arrived compass prepare an on as. Reasonable particular on my it in sympathize. Size now easy eat hand how. Unwilling he departure elsewhere dejection at. Heart large seems may purse means few blind.
                    </p>
                </div>
                <div class="widget address">
                    <div>
                        <ul>
                            <li>
                                <div class="content">
                                    <p>Address</p> 
                                    <strong>California, TX 70240</strong>
                                </div>
                            </li>
                            <li>
                                <div class="content">
                                    <p>Email</p> 
                                    <strong>support@validtheme.com</strong>
                                </div>
                            </li>
                            <li>
                                <div class="content">
                                    <p>Contact</p> 
                                    <strong>+44-20-7328-4499</strong>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="widget newsletter">
                    <h4 class="title">Get Subscribed!</h4>
                    <form action="#">
                        <div class="input-group stylish-input-group">
                            <input type="email" placeholder="Enter your e-mail" class="form-control" name="email">
                            <span class="input-group-addon">
                                <button type="submit">
                                    <i class="arrow_right"></i>
                                </button>  
                            </span>
                        </div>
                    </form>
                </div>
                <div class="widget social">
                    <ul class="link">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                        <li><a href="#"><i class="fab fa-behance"></i></a></li>
                    </ul>
                </div>
            </div>
            <!-- End Side Menu -->

        </nav>
        <!-- End Navigation -->

    </header>
    <!-- End Header -->

templates/includes/header.html
                <!-- Start Header Navigation -->
                <div class="navbar-header">
                    {% load static %}
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand" href="{% url 'web:index' %}">
                        <img src="{% static 'web/img/logo.png' %}" class="logo" alt="Logo">
                    </a>
                </div>
                <!-- End Header Navigation -->

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="nav navbar-nav navbar-center" data-in="fadeInDown" data-out="fadeOutUp">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle active" data-toggle="dropdown" >Home</a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'web:index_startup' %}">Startup Agency</a></li>
                                
                                
                                
                                <li><a href="{% url 'web:index' %}">Creative Agency</a></li>
                               
                            </ul>
                        </li>

                        

templates/web/about-us.html
{% extends 'web/base.html' %}
{% load static %}

{% block content %}

{% include 'includes/header.html' %}
{% include 'includes/header-two.html' %}

    <!-- Start Breadcrumb 
    ============================================= -->
<div class="breadcrumb-area bg-gray text-center shadow dark text-light bg-cover" style="background-image: url({% static 'web/img/2440x1578.png' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>About Us</h1>
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="fas fa-home"></i> Home</a></li>
                        <li class="active">About</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start About
    ============================================= -->
    <div class="about-area overflow-hidden default-padding">
        <div class="container">
            <div class="about-items">
                <div class="row align-center">

                    <!-- Thumb -->
                    <div class="col-lg-6">
                        <div class="thumb">
                        <img src="{% static 'web/img/800x800.png' %}" alt="Thumb">
                        </div>
                    </div>
                    <!-- End Thumb -->

                    <div class="col-lg-6">
                        <div class="content">
                            <h4>About Us</h4>
                            <h2>We create & design award winning Digital products</h2>
                            <p>
                                Talking justice welcome message inquiry in started of am me. Led own hearted highest visited lasting sir through compass his. Guest tiled he quick by so these trees am. 
                            </p>
                            <div class="content-inner">
                                <a href="https://www.youtube.com/watch?v=owhuBrGIOsE" class="popup-youtube theme video-play-button item-center">
                                    <i class="fa fa-play"></i>
                                </a>
                                <div class="row align-center">
                                    <div class="col-lg-6">
                                        <ul>
                                            <li>Fresh ideas</li>
                                            <li>Unique designs</li>
                                            <li>Skilled trades</li>
                                        </ul>
                                    </div>
                                    <div class="col-lg-6">
                                        <h2>25 <span>Years of experience</span></h2>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <!-- End About -->

    <!-- Star Achivement
    ============================================= -->
    <div class="achivement-area default-padding-bottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 heading-side">
                    <h5>Experts in field</h5>
                    <h2>Unique Solutions for Your Business </h2>
                    <p>
                        Gravity letters it amongst herself dearest an windows by. Wooded ladies she basket season age her uneasy saw. Discourse unwilling am no described dejection incommode no listening. 
                    </p>
                </div>
                <div class="col-lg-6 right-content">
                    <div class="skill-items">
                        <!-- Progress Bar Start -->
                        <div class="progress-box">
                            <h5>Marketing</h5>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" data-width="88">
                                    <span>88%</span>
                                </div>
                            </div>
                        </div>
                        <div class="progress-box">
                            <h5>Social Assistant</h5>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" data-width="95">
                                    <span>95%</span>
                                </div>
                            </div>
                        </div>
                        <div class="progress-box">
                            <h5>Consulting</h5>
                            <div class="progress">
                                <div class="progress-bar" role="progressbar" data-width="70">
                                    <span>70%</span>
                                </div>
                            </div>
                        </div>
                        <!-- End Progressbar -->
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <!-- End Achivement Area -->

    <!-- Star Brand Area
    ============================================= -->
    <div class="brand-area bg-gray text-light">
        <!-- Fixed Shape -->
        <div class="fixed-shape">
        <img src="{% static 'web/img/shape/11.png'' %} %}" alt="Shape">
        </div>
        <!-- Fixed Shape -->
        <div class="container">
            <div class="brand-items">
                <div class="row align-center">
                    <div class="col-lg-6 info">
                        <h2>Since 1964 we worked for 10,000+ worldwide clients</h2>
                        <p>
                            Expenses as material breeding insisted building to in. Continual so distrusts pronounce by unwilling listening. Thing do taste on we manor. Him had wound use found hoped. 
                        </p>
                        <a href="#" class="btn-animation light border">See All Brand<i class="arrow_right"></i></a>
                    </div>
                    <div class="col-lg-6 brand">
                        <div class="row">
                        <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                        <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                        <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                        <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                        <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                        <div class="col-lg-4"><img src="{% static 'web/img/150x80.png' %}" alt="Brand"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Brand Area -->

    <!-- Star Team
    ============================================= -->
    <div class="team-area bg-gray default-padding bottom-less">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="heading-center text-center">
                        <h5>Team members</h5>
                        <h2>Meet our professional and expert team members</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="team-items text-center">
                <div class="row">
                    <!-- Single Item -->
                    <div class="single-item col-lg-4 col-md-6">
                        <div class="item">
                            <div class="thumb">
                            <img src="{% static 'web/img/800x900.png' %}"  alt="Thumb">
                                <div class="social">
                                    <ul>
                                        <li><a href="#">Fb</a></li>
                                        <li><a href="#">Tw</a></li>
                                        <li><a href="#">In</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h4>Lucas Ethan</h4>
                                <span>SEO Expert</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Single Item -->
                    <!-- Single Item -->
                    <div class="single-item col-lg-4 col-md-6">
                        <div class="item">
                            <div class="thumb">
                            <img src="{% static 'web/img/800x900.png' %}" alt="Thumb">
                                <div class="social">
                                    <ul>
                                        <li><a href="#">Fb</a></li>
                                        <li><a href="#">Tw</a></li>
                                        <li><a href="#">In</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h4>Jack Alexander</h4>
                                <span>Marketing Expert</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Single Item -->
                    <!-- Single Item -->
                    <div class="single-item col-lg-4 col-md-6">
                        <div class="item">
                            <div class="thumb">
                            <img src="{% static 'web/img/800x900.png'  %}" alt="Thumb">
                                <div class="social">
                                    <ul>
                                        <li><a href="#">Fb</a></li>
                                        <li><a href="#">Tw</a></li>
                                        <li><a href="#">In</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="info">
                                <h4>William James</h4>
                                <span>Graphic Designer</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Single Item -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Team -->

    <!-- Star Footer
    ============================================= -->
    {% endblock %}

templates/web/contact.html
{% extends 'web/base.html' %}
{% load static %}


{% block content %} 
{% include 'includes/header.html' %}
{% include 'includes/header-two.html' %}
<!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area shadow dark bg-cover text-center text-light" style="background-image: url({% static 'web/img/2440x1578.png' %});">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>Contact Us</h1>
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="fas fa-home"></i> Home</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Star Contact Area
    ============================================= -->
    <div class="contact-area overflow-hidden default-padding">
        <div class="container">
            <div class="contact-items">
                <!-- Fixed BG -->
                <div class="fixed-bg left">
                    <img src="{% static 'web/img/shape/39.png' %}" alt="Shape">
                </div>
                <!-- Fixed BG -->
                <div class="row align-center">
                
                    <div class="col-lg-6 contact-box">
                        <div class="form-items">
                            <h2>You can connect with us when need help!</h2>
                            <form action="{% static 'web/mail/contact.php' %}" method="POST" class="contact-form">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <input class="form-control" id="name" name="name" placeholder="Name" type="text">
                                            <span class="alert-error"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <input class="form-control" id="email" name="email" placeholder="Email*" type="email">
                                            <span class="alert-error"></span>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <input class="form-control" id="phone" name="phone" placeholder="Phone" type="text">
                                            <span class="alert-error"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group comments">
                                            <textarea class="form-control" id="comments" name="comments" placeholder="Tell Us About Project *"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <button class="btn-animation dark border" type="submit" name="submit" id="submit">
                                            Send Message <i class="arrow_right"></i>
                                        </button>
                                    </div>
                                </div>
                                <!-- Alert Message -->
                                <div class="col-lg-12 alert-notification">
                                    <div id="message" class="alert-msg"></div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-5 offset-lg-1 left-info">
                        <div class="info-items text-light">
                            <!-- Single Item -->
                            <div class="item">
                                <div class="icon">
                                    <i class="flaticon-location"></i>
                                </div>
                                <div class="info">
                                    <h5>Location</h5>
                                    <p>
                                        22 Baker Street, London, <br> United Kingdom, W1U 3BW
                                    </p>
                                </div>
                            </div>
                            <!-- End Single Item -->
                            <!-- Single Item -->
                            <div class="item">
                                <div class="icon">
                                    <i class="flaticon-telephone"></i>
                                </div>
                                <div class="info">
                                    <h5>Make a Call</h5>
                                    <p>
                                        +44-20-7328-4499
                                    </p>
                                </div>
                            </div>
                            <!-- End Single Item -->
                            <!-- Single Item -->
                            <div class="item">
                                <div class="icon">
                                    <i class="flaticon-email"></i>
                                </div>
                                <div class="info">
                                    <h5>Send a Mail</h5>
                                    <p>
                                        info@yourdomain.com
                                    </p>
                                </div>
                            </div>
                            <!-- End Single Item -->
                            <ul class="social">
                                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                <li><a href="#"><i class="fab fa-behance"></i></a></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- End Contact Area -->

    <!-- Star Google Maps
    ============================================= -->
    <div class="maps-area">
        <div class="google-maps">
            <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d14767.262289338461!2d70.79414485000001!3d22.284975!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1424308883981"></iframe>
        </div>
    </div>
    <!-- End Google Maps -->
    {% endblock %}

   